apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sonxurxo-com-tls
spec:
  secretName: sonxurxo-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sonxurxo.com
  dnsNames:
    - sonxurxo.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sonxurxo.com